{
  try {
    return (int)number;
  }
 catch (  Exception e) {
    return 0;
  }
}
